package handshake

const (
	HANDSHAKE_CMD_REPLCONF             = "REPLCONF"
	HANDSHAKE_CMD_PSYNC                = "PSYNC"
	HANDSHAKE_CMD_RESPONSE_FULL_RESYNC = "FULLRESYNC"
	HANDSHAKE_CMD_RESPONSE_ACK         = "ACK"
	HANDSHAKE_CMD_LISTENING_PORT       = "LISTENING-PORT"
)
